### ISSUE TITLE
Include new dlc

### ISSUE THREAD

**Issue by ImUrX** [Luffyyy/PAYDAY-2-Hashlist#3]
I honestly would like to see the new dlcs being implemented

**Comment by polarathene** [comment]
Is the issue not knowing the paths to be able to extract properly? If the paths are reasonably predictable based on prior dlc patterns, and the only issue is computing the correct hash/string match, if the length of the unknown portion is not too large it can be brute forced?

Although I thought the assets would still be extracted, but as their hash value, rather than original string path?

**Comment by ImUrX** [comment]
i can get their hash value but how do i know what is what? im totally a noob at this

**Comment by polarathene** [comment]
I'd need to understand the actual barrier you're running into, as I haven't done anything with the game assets in years.

Is the assets in anyway actually being extracted? Is there a bundle for them or some error being run into? Do you just need the strings in the hashlist?

I'm not familiar with the process of supporting newer assets such as DLC. If it's just a matter of improving the hashlist strings, then that's not difficult to solve if you only have to guess a small dynamic portion of the string that needs to match a hash value.

**Comment by kythyria** [comment]
Most of the files and bone names added by the newer DLCs are gotten by now. I actually suspect a lot of the ~2.8k remaining files are duplicates.
